/*
 * FW_InitExpansión3.c
 *
 *  Created on: 07/09/2013
 *      Author: marcelo
 */

#include "RegsLPC1769.h"
#include "FW_GPIO.h"
#include "KitInfo2_BaseBoard.h"

void Inicializar_Display7s(void) {

	SetPINSEL(EXPANSION0, PINSEL_GPIO);
	SetPINSEL(EXPANSION1, PINSEL_GPIO);
	SetPINSEL(EXPANSION2, PINSEL_GPIO);
	SetPINSEL(EXPANSION3, PINSEL_GPIO);
	SetPINSEL(EXPANSION4, PINSEL_GPIO);
	SetPINSEL(EXPANSION5, PINSEL_GPIO);
	//SetPINSEL(EXPANSION6, PINSEL_GPIO);

	SetDIR(EXPANSION0, SALIDA);
	SetDIR(EXPANSION1, SALIDA);
	SetDIR(EXPANSION2, SALIDA);
	SetDIR(EXPANSION3, SALIDA);
	SetDIR(EXPANSION4, SALIDA);
	SetDIR(EXPANSION5, SALIDA);
//	SetDIR(EXPANSION6, SALIDA);

}

void Inicializar_TecladoMatricial(void) {

	SetPINSEL(EXPANSION7, PINSEL_GPIO);
	SetPINSEL(EXPANSION8, PINSEL_GPIO);
	SetPINSEL(EXPANSION9, PINSEL_GPIO);
	SetPINSEL(EXPANSION10, PINSEL_GPIO);
	//SetPINSEL(EXPANSION11, PINSEL_GPIO);
	SetPINSEL(EXPANSION12, PINSEL_GPIO);

	SetDIR(EXPANSION7, ENTRADA);
	SetDIR(EXPANSION8, ENTRADA);
	SetDIR(EXPANSION9, ENTRADA);
	SetDIR(EXPANSION10, ENTRADA);
//	SetDIR(EXPANSION11, SALIDA);
	SetDIR(EXPANSION12, SALIDA);

}

void Inicializar_Expansion3(void){

	Inicializar_Display7s();
	Inicializar_TecladoMatricial();

}
